-- insert department table

alter table employees disable constraint DEPARTMENT_FK;

TRUNCATE TABLE DEPARTMENTS;

INSERT INTO DEPARTMENTS(DEPARTMENT_ID,DEPARTMENT_NAME,LOCATION) VALUES (1,'Management', 'London');
INSERT INTO DEPARTMENTS(DEPARTMENT_ID,DEPARTMENT_NAME,LOCATION) VALUES (2,'Engineering', 'Cardiff');
INSERT INTO DEPARTMENTS(DEPARTMENT_ID,DEPARTMENT_NAME,LOCATION) VALUES (3,'Research '||chr(38)||' Development', 'Edinburgh');
INSERT INTO DEPARTMENTS(DEPARTMENT_ID,DEPARTMENT_NAME,LOCATION) VALUES (4,'Sales','Belfast');

alter table employees enable constraint DEPARTMENT_FK;

COMMIT;


-- insert employees table
alter session set NLS_DATE_FORMAT = 'dd/mm/rr';

alter table employees disable constraint MANAGER_FK;

truncate table employees;

INSERT INTO employees(EMPLOYEE_ID,EMPLOYEE_NAME,JOB_TITLE,MANAGER_ID,DATE_HIRED,SALARY,DEPARTMENT_ID) values (90001 ,'John Smith'		,'CEO' 			,null		,'01/01/95',100000,1);
INSERT INTO employees(EMPLOYEE_ID,EMPLOYEE_NAME,JOB_TITLE,MANAGER_ID,DATE_HIRED,SALARY,DEPARTMENT_ID) values (90002 ,'Jimmy Willi'		,'Manager' 		,90001 		,'23/09/03',52500 ,4);
INSERT INTO employees(EMPLOYEE_ID,EMPLOYEE_NAME,JOB_TITLE,MANAGER_ID,DATE_HIRED,SALARY,DEPARTMENT_ID) values (90003 ,'Roxy Jones'		,'Salesperson' 	,null		,'11/02/17',35000 ,4);
INSERT INTO employees(EMPLOYEE_ID,EMPLOYEE_NAME,JOB_TITLE,MANAGER_ID,DATE_HIRED,SALARY,DEPARTMENT_ID) values (90004 ,'Selwyn Field'		,'Salesperson' 	,null		,'20/05/15',32000 ,4);
INSERT INTO employees(EMPLOYEE_ID,EMPLOYEE_NAME,JOB_TITLE,MANAGER_ID,DATE_HIRED,SALARY,DEPARTMENT_ID) values (90005 ,'David Hallett'	,'Engineer' 	,90006		,'17/04/18',40000 ,2);
INSERT INTO employees(EMPLOYEE_ID,EMPLOYEE_NAME,JOB_TITLE,MANAGER_ID,DATE_HIRED,SALARY,DEPARTMENT_ID) values (90006 ,'Sarah Phelps' 	,'Manager' 		,90001 		,'21/03/15',45000 ,2);
INSERT INTO employees(EMPLOYEE_ID,EMPLOYEE_NAME,JOB_TITLE,MANAGER_ID,DATE_HIRED,SALARY,DEPARTMENT_ID) values (90007 ,'Louise Harper' 	,'Engineer' 	,90006 		,'01/01/13',47000 ,2);
INSERT INTO employees(EMPLOYEE_ID,EMPLOYEE_NAME,JOB_TITLE,MANAGER_ID,DATE_HIRED,SALARY,DEPARTMENT_ID) values (90008 ,'Tina Hart' 		,'Engineer' 	,90009 		,'28/07/14',45000 ,3);
INSERT INTO employees(EMPLOYEE_ID,EMPLOYEE_NAME,JOB_TITLE,MANAGER_ID,DATE_HIRED,SALARY,DEPARTMENT_ID) values (90009 ,'Gus Jones' 		,'Manager' 		,90001 		,'15/05/18',50000 ,3);

alter table employees enable constraint MANAGER_FK;

commit;

